context("Performance Stats Preparation")

library(podlover)

# prepare for tests
t_exmpl <- podlove_create_example(clean = TRUE, 
																	seed = 1,
																	n_posts = 30, 
																	n_episodes = 30)

t_perf_1 <- podlove_performance_stats(df_tidy_data = t_exmpl, 
																		launch = Inf, 
																		post_launch = 0, 
																		limit_unit = "days")

t_perf_2 <- podlove_performance_stats(df_tidy_data = t_exmpl, 
																		launch = 3, 
																		post_launch = 30, 
																		limit_unit = "days")

t_perf_3 <- podlove_performance_stats(df_tidy_data = t_exmpl, 
																		launch = 72, 
																		post_launch = 720, 
																		limit_unit = "hours")

# generated by dput(object)
r_dls <- c(24L, 252L, 35L, 77L, 149L, 87L, 257L, 211L, 179L, 45L, 139L, 
					 54L, 110L, 271L, 128L, 119L, 191L, 223L, 96L, 255L, 274L, 66L, 
					 157L, 290L, 243L, 202L, 320L, 233L, 171L, 299L)

r_dlspd <- c(0.8, 0.731229597388466, 0.821917808219178, 0.828699551569507, 
						 0.823204419889503, 0.824644549763033, 0.804486761445155, 0.822478479779113, 
						 0.818129880022853, 0.81570996978852, 0.825333993072736, 0.797047970479705, 
						 0.841836734693878, 0.816162630191994, 0.821390374331551, 0.830715532286213, 
						 0.825499729875743, 0.828611240130051, 0.812985179957657, 0.830957230142566, 
						 0.716574043805165, 0.821576763485477, 0.811020232458028, 0.811851160620553, 
						 0.82571145405635, 0.82801024765158, 0.810212047684355, 0.827096583345659, 
						 0.829426030719483, 0.80856338028169)

r2_dlpdat <- c(1.09090909090909, 55.5428571428571, 11.2340425531915, 11.4782608695652, 
							23.3333333333333, 13.3333333333333, 55.2727272727273, 32.9142857142857, 
							30.6666666666667, 12.2181818181818, 25.7647058823529, 8.12307692307692, 
							16, 47.3239436619718, 25.7391304347826, 13.6666666666667, 37.0588235294118, 
							34, 10.4347826086957, 45.2571428571429, 61.0588235294118, 7.88059701492537, 
							30.9565217391304, 50.3661971830986, 35.3333333333333, 27.3333333333333, 
							49.6666666666667, 44.5714285714286, 28.8, 54.4225352112676)

r2_dlpdaft <- c(0.0333333333333333, 0.237939789626405, 0.0939334637964775, 
							 0.247533632286996, 0.171270718232044, 0.218009478672986, 0.262945089343942, 
							 0.272860159168426, 0.237669015425633, 0.181268882175227, 0.20781791192479, 
							 0.22140221402214, 0.191326530612245, 0.249968628435186, 0.205347593582888, 
							 0.25130890052356, 0.246353322528363, 0.230376219228983, 0.245589273112209, 
							 0.276985743380855, 0.240601503759398, 0.186721991701245, 0.237623762376238, 
							 0.240755861425405, 0.295625088489311, 0.278736122971819, 0.291169954636565, 
							 0.255583493566041, 0.257073565076799, 0.224450704225352)


# tests
test_that("dimensions of dfs are correct", {
	
	expect_equal(nrow(t_perf_1), 30)
	expect_equal(nrow(t_perf_2), 30)
	expect_equal(nrow(t_perf_3), 30)
	
	expect_equal(ncol(t_perf_1), 5)
	expect_equal(ncol(t_perf_2), 5)
	expect_equal(ncol(t_perf_3), 5)
})

test_that("col names of dfs are correct", {
	
	cnam <- function(df, i) {
		nams <- colnames(df)
		
		nams[i]
	} 
	
	expect_equal(cnam(t_perf_1, 1), "title")
	expect_equal(cnam(t_perf_1, 2), "dls")
	expect_equal(cnam(t_perf_1, 3), "dls_per_day")
	expect_equal(cnam(t_perf_1, 4), "dls_per_day_at_launch")
	expect_equal(cnam(t_perf_1, 5), "dls_per_day_after_launch")
	
	expect_equal(cnam(t_perf_2, 1), "title")
	expect_equal(cnam(t_perf_2, 2), "dls")
	expect_equal(cnam(t_perf_2, 3), "dls_per_day")
	expect_equal(cnam(t_perf_2, 4), "dls_per_day_at_launch")
	expect_equal(cnam(t_perf_2, 5), "dls_per_day_after_launch")
	
	expect_equal(cnam(t_perf_3, 1), "title")
	expect_equal(cnam(t_perf_3, 2), "dls")
	expect_equal(cnam(t_perf_3, 3), "dls_per_hour")
	expect_equal(cnam(t_perf_3, 4), "dls_per_hour_at_launch")
	expect_equal(cnam(t_perf_3, 5), "dls_per_hour_after_launch")
})

test_that("col classes of dfs are correct", {
	
	expect_is(t_perf_1$title, "character")
	expect_is(t_perf_1$dls, "integer")
	expect_is(t_perf_1$dls_per_day, "numeric")
	expect_is(t_perf_1$dls_per_day_at_launch, "numeric")
	expect_is(t_perf_1$dls_per_day_after_launch, "numeric")
	
	expect_is(t_perf_2$title, "character")
	expect_is(t_perf_2$dls, "integer")
	expect_is(t_perf_2$dls_per_day, "numeric")
	expect_is(t_perf_2$dls_per_day_at_launch, "numeric")
	expect_is(t_perf_2$dls_per_day_after_launch, "numeric")
	
	expect_is(t_perf_3$title, "character")
	expect_is(t_perf_3$dls, "integer")
	expect_is(t_perf_3$dls_per_hour, "numeric")
	expect_is(t_perf_3$dls_per_hour_at_launch, "numeric")
	expect_is(t_perf_3$dls_per_hour_after_launch, "numeric")
	
})

test_that("content of dfs are correct", {
	
	expect_equal(t_perf_1$dls, r_dls)
	expect_equal(t_perf_1$dls_per_day, r_dlspd)
	expect_equal(t_perf_1$dls_per_day_at_launch, r_dlspd)
	expect_equal(t_perf_1$dls_per_day_after_launch, r_dlspd)
	
	expect_equal(t_perf_2$dls, r_dls)
	expect_equal(t_perf_2$dls_per_day, r_dlspd)
	expect_equal(t_perf_2$dls_per_day_at_launch, r2_dlpdat)
	expect_equal(t_perf_2$dls_per_day_after_launch, r2_dlpdaft)
	
	expect_equal(t_perf_3$dls, r_dls)
	expect_equal(t_perf_3$dls_per_hour, r_dlspd / 24)
	expect_equal(t_perf_3$dls_per_hour_at_launch, r2_dlpdat / 24)
	expect_equal(t_perf_3$dls_per_hour_after_launch, r2_dlpdaft / 24)
	
})

# cleanup
rm(t_exmpl)
rm(list = ls(pat = "[tr]_perf_[123]"))
